### ISSUE TITLE
Is it possible to set property of Text components like numberOfLines, ellipsizeMode  to Highlighter

### ISSUE THREAD

**Issue by dongawli** [clauderic/react-native-highlight-words#12]
Hi guys,
Thank you for simple and very useful Highlighter component.
Is it possible to set property of Text components like numberOfLines, ellipsizeMode  to Highlighter ?
I've added above properties to style but its not working.

**Comment by clauderic** [comment]
Hey @dongawli,

You should be able to add these properties directly on `Highlighter` and they will be passed down to the wrapper `<Text>` node
