### ISSUE TITLE
Add multiple styles to other words

### ISSUE THREAD

**Issue by Albert0405** [clauderic/react-native-highlight-words#13]
```
const text = "What do you do after school? I do aerobics after school."
<Text>
     <Highlighter
           highlightStyle={{ color: 'red' }}
           searchWords={["What", "do"]}
           textToHighlight={text}
     />
</Text>
```
This something i wanted to achieve

![90327d00-3b0a-11e7-9469-e2aa8b13bb8a](https://user-images.githubusercontent.com/38030623/41193629-5022ce54-6c41-11e8-853a-a318d2915f10.png)

**Comment by clauderic** [comment]
This isn't supported by this library, and I don't have plans to work on this functionality myself. If you'd like to submit a PR to add this functionality, we can discuss about it there.
